# /etc/tmpfiles.d/fbjq-setup.conf
#
# * systemd-tmpfiles --create /etc/tmpfiles.d/fbjq-setup.conf
#
# Type  Path                      Mode  User  Group  Age  Argument
d       /run/fbjq                 0755  root  root   -    -
d       /var/spool/fbjq/tmp       0700  root  root   1h   -
d       /var/spool/fbjq/delivery  0700  root  root   -    -
d       /var/spool/fbjq/dead      0700  root  root   1d   -
d       /var/spool/fbjq/queue     0755  root  root   -    -
