# /etc/tmpfiles.d/fbjq-setup.conf
#
# * systemd-tmpfiles --create etc/tmpfiles.d/setup-fbjq.conf
#
# [DEBUG]
# Type  Path                Mode  User  Group  Age  Argument
d       /run/fbjq           0755  root  root   -    -
d       /var/fbjq/tmp       0700  root  root   1h   -
d       /var/fbjq/delivery  0700  root  root   -    -
d       /var/fbjq/dead      0700  root  root   1d   -
d       /var/fbjq/queue     0755  root  root   -    -

# [RELEASE]
## Type  Path                Mode  User  Group  Age  Argument
#d       /var/fbjq/tmp       0700  root  root   1h   -
#d       /var/fbjq/delivery  0700  root  root   -    -
#d       /var/fbjq/dead      0700  root  root   1d   -
#d       /var/fbjq/queue     0755  root  root   -    -
