
# /etc/fbjq.conf
version = "0010";

spool_dir = "/var/spool/fbjq";

queue: {
    alice: {
        exec_user: "user";
        allow_group: "alice-group";
    };

    bob: {
        exec_user: "user";
        allow_group: "bob-group";
        max_process: 4;
    };
};
