# /etc/fbjq.conf
version = "1.0";
spool_dir = "/var/spool/fbjq";

queue: {
    alice: {
        exec_user: "user";
        exec_group: "gnome-remote-desktop";
        allow_group: "alice-group";
        max_process: 2;
    };

    bob: {
        exec_user: "user";
        allow_group: "bob-group";
        max_process: 4;
    };
};
